In [86]:
import numpy as np
import math
import time

In [2]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.shape

(3, 3)

In [5]:
a[2,1]

np.int64(8)

In [6]:
a.ndim

2

In [7]:
b = np.arange(1,21)
c = np.full([1,10],10)
# b.shape = (5,10)
# print(b)
# b[2:5,-3:3:-1]

In [8]:
np.exp(b)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [9]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [10]:
neg = np.arange(-10,11)
print(neg)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]


In [11]:
np.absolute(neg)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10])

In [12]:
np.max(neg)

np.int64(10)

In [13]:
np.sign(neg)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1])

In [14]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [15]:
np.multiply(c,b)

ValueError: operands could not be broadcast together with shapes (1,10) (20,) 

In [ ]:
b.view()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# d = b.copy()
# print(b)
# print(d)
# b[0]=23
# print(b)
# print(d)

In [ ]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
b.shape = (2,10)

In [ ]:
for x in np.nditer(b):
    print(x)
# for x in b:
#     for y in x:
#         print(y,end="...")

In [ ]:
# import numpy as np
# from io import StringIO
# with open('lists.txt','r') as in_file:
#     in_text= in_file.read()
# l1 = list(in_text)
# #l1 = str(in_text.split("\n"))
# print((l1))
# arr = np.genfromtxt(StringIO(l1), delimiter=",")
# # print(arr)

In [ ]:
n = 11
current = 1
for i in range(1,n):
    for j in range(1,i):
        print(f"{current} ",end=" ")
        current +=1
    print("\n")
    

July 22 Code

In [ ]:
# arr = np.random.randint(1,10,size=10)
# arr = (np.sort(arr))
#print(arr)
#np.unique_counts(0)
np.arange(1,10**3)

In [13]:
# m = np.unique_counts(arr)
# print(m)
# print(m[1])

UniqueCountsResult(values=array([1, 2, 3, 5, 7, 9]), counts=array([2, 1, 3, 1, 1, 2]))
[2 1 3 1 1 2]


In [104]:
# m = np.where(arr%2==0)
# n = np.where(arr%2==1)
# print(f"Array indices with even elements: {m[0]}")
# print(f"Array indices with odd elements: {n[0]}")
print(10**6)

1000000


In [108]:
arr = np.arange(1,10**3)
#print(arr)
starting = time.perf_counter()
def is_prime(n):
    if n%2==0 and n>2:
        return False
    #return all(n%i for i in range(3,n,2))
    return all(n%i for i in range(3,int(math.sqrt(n))+1,2))

vfunc = np.vectorize(is_prime)
filtered = vfunc(arr)
primes = np.extract(filtered,arr)
finished = time.perf_counter()
print(primes)
print(f"{round(finished-starting,3)} seconds.")

# for num in arr:
#     for i in range(1,num):
#         if num%i==0:
#             prime_filter.append(False)
#         else:
#             prime_filter.append(True)
# print(prime_filter)
# print(arr[prime_filter])

[  1   2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59
  61  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149
 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241
 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353
 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461
 463 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587
 593 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691
 701 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823
 827 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947
 953 967 971 977 983 991 997]
0.002 seconds.
