In [1]:
import numpy as np
from scipy import stats as st

In [2]:
a1 = np.random.randint(1,10,10)
print(a1)
print(len(a1))

[6 5 6 3 1 4 5 4 4 5]
10


In [3]:
a1 = np.sort(a1)
print(a1)
print(f"Mean of array: {np.mean(a1)}")

[1 3 4 4 4 5 5 5 6 6]
Mean of array: 4.3


In [4]:
print(f"Median of array: {np.median(a1)}")

Median of array: 4.5


In [5]:
print(np.std(a1))

1.4177446878757827


In [7]:
print(st.mode(a1))

ModeResult(mode=np.int64(4), count=np.int64(3))


In [26]:
arr = np.arange(0,16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [56]:
arr_random = np.random.randint(0,100,10)
arr_random = np.sort(arr_random)
arr_random

array([ 7, 11, 20, 20, 20, 26, 40, 62, 81, 98])

In [59]:
arr_mean = np.mean(arr_random)
arr_sd = np.std(arr_random)
print("mean:",arr_mean,"Standard deviation: ",arr_sd)
arr_normalized = (arr_random-arr_mean)/arr_sd
print("Normalized array: ",arr_normalized)
print(round(np.mean(arr_normalized)))
print(round(np.std(arr_normalized)))

mean: 38.5 Standard deviation:  29.71952220342716
Normalized array:  [-1.05990937 -0.9253177  -0.62248645 -0.62248645 -0.62248645 -0.42059896
  0.05047187  0.79072604  1.43003645  2.00205103]
0
1


In [77]:
arr1 = np.random.randint(1,11,size=(5,5))
arr2 = np.random.randint(1,11,size=(5,5))
#print("Array 1:\n",arr1,"\nArray 2:\n",arr2)
added = np.add(arr1,arr2)
print("Added arrays:\n",added)
subtracted = np.subtract(arr1,arr2)
print("Subtracted arrays:\n",subtracted)
multiplied = np.multiply(arr1,arr2)
print("Multiplied arrays:\n",multiplied)
divided = np.divide(arr1,arr2)
print("Divided arrays:\n",divided)

Added arrays:
 [[19  9  4  6 10]
 [15  3 13  7 11]
 [17  4  6 17  7]
 [10 10 10 12 14]
 [ 5 15  9  7 10]]
Subtracted arrays:
 [[-1 -7  0  2 -4]
 [-1  1  7  1 -7]
 [ 1 -2 -4 -1  1]
 [ 2  2  6  0  2]
 [ 1  3  1 -5  0]]
Multiplied arrays:
 [[90  8  4  8 21]
 [56  2 30 12 18]
 [72  3  5 72 12]
 [24 24 16 36 48]
 [ 6 54 20  6 25]]


TypeError: type numpy.ndarray doesn't define __round__ method

In [84]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])